# Pandas Practice — Stack Overflow Developer Survey 2025

Practicing pandas fundamentals (import, reading CSV, exploring a DataFrame) using a real, large, messy dataset instead of a toy example — the 2025 Stack Overflow Developer Survey (49,191 responses, 172 columns).

## Setup
Import pandas — the core library for working with tabular data in Python.

In [ ]:
import pandas as pd

## Load the data and the schema (column reference)
Read the raw survey responses into a DataFrame. The survey has 172 columns with non-obvious names — `schema.csv` maps each column code to its full question text.

**New:** using `index_col` to set a meaningful column as the row label instead of the default 0,1,2... — `ResponseId` for the main data, and `qname` (the column code) for the schema, so each row can be looked up directly by its natural identifier.

In [ ]:
df = pd.read_csv('data/results.csv', index_col='ResponseId')
schema_df = pd.read_csv('data/schema.csv', index_col='qname')

## Inspect the data
Display the full DataFrame to get a first look at the structure.

In [43]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community)","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a new career or industry,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;Google Cloud;Gradle,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn;Medium",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image generating models;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search for answers,Project planning;Deployment and monitoring;Learning new concepts or technologies,Documenting code;Debugging or fixing code;Testing code;Committing and reviewing code;Predictive analytics;Generating content or synthetic data;Creating or maintaining documentation,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI agents have reduced the time spent on specific development tasks.,AI agents have helped me automate repetitive tasks.;AI agents have improved the quality of my code.;AI agents have accelerated my learning about new technologies or codebases.;AI agents have helped me solve complex problems more effectively.;AI agents have improved collaboration within my team.,NaN,NaN,NaN,I am concerned about the accuracy of the information provided by AI agents.;It takes significant time and effort to learn how to use AI agents effectively.,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security and privacy of data when using AI agents.,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibility)",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or industry voluntarily,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,"Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;Twitch;LinkedIn;Substack;Medium","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;Twitch;LinkedIn;Substack;Medium","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;Twitch;LinkedIn;Substack;Medium",NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year","Chat (people);Message Boards;Long-form articles;Videos;Coding challenges;Logic games/puzzles;Lists of recommendations (tools, frameworks, technologies, etc.);Direct messaging of users;Job board;Day-in-the-life profiles/interviews with experts",6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Committing and reviewing code;Deployment and monitoring,Writing code;Documenting code;Debugging or fixing code;Testing code;Predictive analytics;Search for answers;Generating content or synthetic data;Creating or maintaining documentation,NaN,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns about the security and privacy of data when using AI agents.,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I want to compare different solutions;When I have ethical or security concerns about code,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-employed",None of the above,10.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Videos (not associated with specific online course or certification);Technical documentation (is generated for/by the tool or system),"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps;Technical documentation (is generated for/by the tool or system);Videos (not associated with specific online course or certification),12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or industry involuntarily,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI GPT (chatbot models),Gemini (Flash general purpose models);Gemini (Pro Reasoning models);openAI GPT (chatbot models),Gemini (Flash general purpose models);openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year","Chat (people);Videos;Lists of recommendations (tools, frameworks, technologies, etc.);Chat (bot/AI)",3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Testing code;Creating or maintaining documentation;Learning new concepts or technologies,NaN,Project planning;Committing and reviewing code;Deployment and monitoring;Predictive analytics;Search for answers,Learning about a codebase;Writing code;Generating content or synthetic data,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI agents have helped me automate repetitive tasks.;AI agents have accelerated my learning about new technologies or codebases.;AI agents have reduced the time spent on specific development tasks.,AI agents have improved the quality of my code.;AI agents have helped me solve complex problems more effectively.,AI agents have improved collaboration within my team.,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,I am concerned about the accuracy of the information provided by AI agents.;Integrating AI agents with my existing tools and workflows can be difficult.;I have concerns about the security and privacy of data when using AI agents.,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem,"Understand how things actually work, problem solving, and algorithms",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies","AI CodeGen tools or AI-enabled apps;Videos (not associated with specific online course or certification);Other online resources (e.g. standard search, forum, online community)",5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a new career or industry,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Overflow,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code;Committing and reviewing code;Deployment and monitoring;Creating or maintaining documentation,Learning about a codebase;Writing code;Debugging or fixing code;Predictive analytics,Search for answers;Generating content or synthetic data;Learning new concepts or technologies,NaN,"AI solutions that are almost right, but not quite;I don’t use AI tools regularly",NO,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about new technologies or codebases.,AI agents have increased my productivity.;AI agents have improved the quality of my code.;AI agents have helped me solve complex problems more effectively.;AI agents have reduced the time spent on specific development tasks.;AI agents have improved collaboration within my team.,AI agents have helped me automate repetitive tasks.,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns about the security and privacy of data when using AI agents.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,Integrating AI agents with my existing tools and workflows can be difficult.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem,NaN,36197.0,6.0

`head()` shows just the first 5 rows — a quicker way to preview the data without printing all 49,191 rows.

In [ ]:
df.head()

`shape` returns (rows, columns) — a quick way to check the size of the dataset.

In [ ]:
df.shape

## Display settings
By default, pandas truncates wide/long output with `...`. `set_option` overrides this so all 172 columns and up to 139 rows display in full — useful for exploring a wide dataset like this one.

**Note:** the value and the option name must be two separate arguments — `'display.max_columns', 172` — not one string with the comma inside the quotes (that was an early mistake here, same trap as a misplaced comma in a SQL string literal).

In [ ]:
pd.set_option('display.max_columns', 172)
pd.set_option('display.max_rows', 139)

## List all column names
Wrapping `df.columns` in `list()` forces pandas to print every column name in full — useful for scanning all 172 question codes before deciding which ones to explore.

In [ ]:
list(df.columns)

## Explore a single column
`value_counts()` counts how many times each unique value appears in a column — the pandas equivalent of `GROUP BY ... COUNT(*)` in SQL.

In [ ]:
df['LearnCodeChoose'].value_counts()

Display the schema to see the question text behind each column code.

In [44]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
TechEndorse_1,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_2,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Costs are manageable,9.0
TechEndorse_13,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Other (please specify): - Text,13.0
TechOppose_1,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Lack of AI or AI agents,1.0
TechOppose_2,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Security or privacy concerns,6.0
TechOppose_11,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Outdated or obsolete technology or features,8.0
TechOppose_16,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Ethical concerns,9.0
TechOppose_15,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Other (please specify): - Text,15.0
JobSatPoints_1,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Control over the level of quality in projects,1.0
JobSatPoints_2,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_16,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,You like your manager,3.0
JobSatPoints_3,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Expert mentors,5.0
JobSatPoints_5,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Opportunities to mentor and lead junior-level coworkers,6.0
JobSatPoints_6,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Job stability and career growth with a single employer,9.0
JobSatPoints_9,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Innovation through solving challenging and complex problems,10.0
JobSatPoints_10,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Other (please specify): - Text,15.0
SO_Actions_1,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Browse content related to Q&A posts I recently viewed,1.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Read and/or vote on comments for a Question or Answer I am interested in,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,"Directly open a Q&A post via search, documentation or a peer",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Answer a question,6.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Comment on Q&A posts,7.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Other (write in): - Text,15.0
MainBranch,QID3,Are you someone who writes code? Please select one of the following options that best describes you today.,MC,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the highest level of formal education that you’ve completed?,MC,NaN,NaN
Employment,QID7,Which of the following best describes your current employment status?<br>,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</strong> activities are you currently engaged in?,MC,NaN,NaN
WorkExp,QID14,"How many years of professional work experience do you have? Please round to the nearest whole number, excluding any decimal points. If your answer is '0', please leave blank.",TE,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new coding skill/programming language in the last year?,MC,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Select all that apply.,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning AI programming or AI-enabled tooling on your own or at work?,MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past year? Select all that apply.,MC,NaN,NaN
YearsCode,QID13,"Including any education, how many years have you been coding in total? Please round to the nearest whole number, excluding any decimal points.",TE,NaN,NaN
DevType,QID15,Which of the following describes your current job or the job you had for the most time in the past year?,MC,NaN,NaN
OrgSize,QID16,"Approximately how many people are employed by your employer? This should only include your primary company, and if there was more than one employer please consider the one you spent most of your time working for in the past year.",MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people manager?,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</strong> a new technology purchase at your organization or sole proprietor job in the past year?,MC,NaN,NaN
TechEndorseIntro,QID33,"When you&rsquo;re in a position to <strong>influence or endorse a technology</strong>, whether at work, for school, or for a personal project you&rsquo;re responsible for, what features or attributes matter most when deciding to support a tool? What factors would be deal-breakers?<br />\n<br />\nFirst, select the context (work, school, personal project). Then, rank the following features in order of importance.​​​​​​",MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professional developer role?,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current job?,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transitioned into a new role in the past year?,MC,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, developer, or technologist) over the past year:\n<br><br>Excluding general operating systems (like Windows or macOS) and web browsers, <b>how many distinct software applications or platforms</b> did you regularly use to create, analyze, manage, or share information in order to do your job?\n\nPlease enter a whole number below with no punctuation, or leave blank.",TE,NaN,NaN
ToolCountPersonal,QID31,"<b></b>For your <b>side projects or other personal work</b> over the past year (focus on the project you spent the most time on if applicable):\n<br><br>Excluding general operating systems and web browsers, how many <b>distinct software applications or platforms</b> did you regularly use to do your job? Please enter a whole number below with no punctuation, or leave blank.",TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in.",MC,NaN,NaN
CompTotal,QID22,"What is your current total <b>annual</b> compensation (salary, bonuses, and perks, before taxes and deductions) in terms of your day-to-day currency? Please enter a whole number in the box below, without any punctuation. If you are paid hourly, please estimate an equivalent yearly salary. If you prefer not to answer, please leave the box empty.",TE,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and markup languages in the last year or do you plan to in the year to come? Here, we are referring to anything you use that is conventionally referred to as code.",MC,NaN,NaN
Language,QID34,"Which <b>programming, scripting, and markup languages</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
LanguagesHaveEntry,QID51,"Was the programming language you use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you used in the past year</strong>.",TE,NaN,NaN
LanguagesWantEntry,QID52,"Was the programming language you want to use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you want to use next year</strong>.",TE,NaN,NaN
DatabaseChoice,QID45,"Did you work with database environments in the last year or do you plan to in the year to come? Here, we are referring to a system of managing structured data, mostly outside of your local machine.",MC,NaN,NaN
Database,QID35,"Which <b>database environments </b>have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
DatabaseHaveEntry,QID54,"Was the database environment you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.",TE,NaN,NaN
DatabaseWantEntry,QID55,"Was the database environment you want to use not listed above? List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>.",TE,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containerization/orchestration tools, package managers, build tools or infrastructure as code solutions in the last year or do you plan to in the year to come? Here, we are referring to tooling that automates, manages, and scales the entire application lifecycle, often leveraging remote, virtualized resources.",MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the platform and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you want to use not listed above? List below, separated by a comma and a space for each, what<strong>you want to use next year</strong>.",TE,NaN,NaN
WebframeChoice,QID47,"Did you work with web frameworks and web technologies in the last year or do you plan to in the year to come? Here, we are referring to technology that helps website and web apps materialize.",MC,NaN,NaN
Webframe,QID37,"Which <b>web frameworks and web technologies</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the framework and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN

## Look up one specific value with `.loc`
`.loc[row_label, column_label]` returns a single value directly — here, the full question text for the row indexed `'ICorPM'`.

**Note:** by default, long text gets truncated with `...`. Fixing this requires a different option than `max_columns` — `pd.set_option('display.max_colwidth', None)` removes the character limit per cell (not shown here to avoid overriding useful truncation elsewhere, but useful to know for reading full question text).

In [ ]:
schema_df.loc['ICorPM', 'question']

## Sort by index
`sort_index()` sorts the DataFrame by its row labels (here, the `qname` codes) rather than by a column's values. `ascending=False` sorts Z→A instead of the default A→Z.

In [45]:
schema_df.sort_index(ascending=False)

,qid,question,type,sub,sq_id
qname,,,,,
YearsCode,QID13,"Including any education, how many years have you been coding in total? Please round to the nearest whole number, excluding any decimal points.",TE,NaN,NaN
WorkExp,QID14,"How many years of professional work experience do you have? Please round to the nearest whole number, excluding any decimal points. If your answer is '0', please leave blank.",TE,NaN,NaN
WebframeWantEntry,QID59,"Were the web frameworks and web technologies you want to use not listed above? List below, separated by a comma and a space for each, the what <strong>you want to use next year</strong>.",TE,NaN,NaN
WebframeHaveEntry,QID58,"Were the web frameworks and web technologies you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.",TE,NaN,NaN
WebframeChoice,QID47,"Did you work with web frameworks and web technologies in the last year or do you plan to in the year to come? Here, we are referring to technology that helps website and web apps materialize.",MC,NaN,NaN
Webframe,QID37,"Which <b>web frameworks and web technologies</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the framework and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, developer, or technologist) over the past year:\n<br><br>Excluding general operating systems (like Windows or macOS) and web browsers, <b>how many distinct software applications or platforms</b> did you regularly use to create, analyze, manage, or share information in order to do your job?\n\nPlease enter a whole number below with no punctuation, or leave blank.",TE,NaN,NaN
ToolCountPersonal,QID31,"<b></b>For your <b>side projects or other personal work</b> over the past year (focus on the project you spent the most time on if applicable):\n<br><br>Excluding general operating systems and web browsers, how many <b>distinct software applications or platforms</b> did you regularly use to do your job? Please enter a whole number below with no punctuation, or leave blank.",TE,NaN,NaN
TechOppose_9,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Security or privacy concerns,6.0
TechOppose_7,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Prohibitive pricing,5.0
TechOppose_5,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Inefficient or time-costly,4.0
TechOppose_3,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Lack of or sub-par API,3.0
TechOppose_2,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Poor usability,2.0
TechOppose_16,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Ethical concerns,9.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Other (please specify): - Text,15.0
TechOppose_15,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Other (please specify):,10.0
TechOppose_13,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Outdated or obsolete technology or features,8.0
TechOppose_11,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Availability of better alternatives,7.0
TechOppose_1,QID19,What would turn you off or cause you to reject it (most to least important)?,RO,Lack of AI or AI agents,1.0
TechEndorse_9,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Costs are manageable,9.0
TechEndorse_8,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Reliability and low latency,8.0
TechEndorse_7,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Good brand and public image,7.0
TechEndorse_6,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Connected to an open-source project,6.0
TechEndorse_5,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Reputation for quality,5.0
TechEndorse_4,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Customizable and manageable codebase,4.0
TechEndorse_3,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Robust and complete API,3.0
TechEndorse_2,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Easy-to-use API,2.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Other (please specify): - Text,13.0
TechEndorse_13,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Other (please specify):,10.0
TechEndorse_1,QID18,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,AI integration or AI Agent capabilities,1.0
TechEndorseIntro,QID33,"When you&rsquo;re in a position to <strong>influence or endorse a technology</strong>, whether at work, for school, or for a personal project you&rsquo;re responsible for, what features or attributes matter most when deciding to support a tool? What factors would be deal-breakers?<br />\n<br />\nFirst, select the context (work, school, personal project). Then, rank the following features in order of importance.​​​​​​",MC,NaN,NaN
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career growth or connecting with a community of developers, is there an alternative to the Q&amp;A format you prefer using today or would like to see on Stack Overflow to get what you need? Select all that apply.",MC,NaN,NaN
SO_Actions_9,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Comment on Q&A posts,7.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Answer a question,6.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Ask a question,5.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,"Directly open a Q&A post via search, documentation or a peer",4.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Bookmark posts to look at later,3.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Read and/or vote on comments for a Question or Answer I am interested in,2.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Other (write in): - Text,15.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Other (write in):,10.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Use discussion or chat feature,9.0
SO_Actions_1,QID76,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Browse content related to Q&A posts I recently viewed,1.0
SOVisitFreq,QID70,How frequently would you say you visit Stack Overflow?,MC,NaN,NaN
SOTagsWant Entry,QID63,"Was the new tag on Stack Overflow (i.e. added in the last 2 - 3 years) you want to use not listed above? List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>.",TE,NaN,NaN
SOTagsHaveEntry,QID62,"Was the new tag on Stack Overflow (i.e. added in the last 2 - 3 years) you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.",TE,NaN,NaN
SOTags,QID39,"Which rising technology of the added as <b>new tag or tag subject area on Stack Overflow</b> in the last three years <strong>have you used</strong> regularly in the past year, and which do you <strong>want to work with</strong> over the next year? Please check all that apply.<br>\n",Matrix,NaN,NaN
SOPartFreq,QID73,"How frequently would you say you participate in Q&amp;A on Stack Overflow? By participate we mean ask, answer, and vote or comment on questions.",MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it a result of encountering issues from AI or AI-enabled tools that require extra time or effort to fix, understand, or debug?",MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack Overflow community?,MC,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</strong> a new technology purchase at your organization or sole proprietor job in the past year?,MC,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you want to use not listed above? List below, separated by a comma and a space for each, what<strong>you want to use next year</strong>.",TE,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.",TE,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containerization/orchestration tools, package managers, build tools or infrastructure as code solutions in the last year or do you plan to in the year to come? Here, we are referring to tooling that automates, manages, and scales the entire application lifecycle, often leveraging remote, virtualized resources.",MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the platform and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
OrgSize,QID16,"Approximately how many people are employed by your employer? This should only include your primary company, and if there was more than one employer please consider the one you spent most of your time working for in the past year.",MC,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in which you work?,Matrix,NaN,NaN
OfficeStackWantEntry,QID65,"Was the collaborative work management and/or code documentation tools you want to use not listed above? List below, separated by a comma and a space for each, what you used in the past year.",TE,NaN,NaN
OfficeStackHaveEntry,QID64,"Was the collaborative work management and/or code documentation tools you use not listed above? List below, separated by a comma and a space for each, what you used in the past year.",TE,NaN,NaN
OfficeStackAsync,QID41,"Which <b>collaborative work management and/or code documentation tools</b> did you use regularly over the past year, and which do you want to work with over the next year? Select all that apply",Matrix,NaN,NaN
NewRole,QID29,Have you considered a career change or transitioned into a new role in the past year?,MC,NaN,NaN
MainBranch,QID3,Are you someone who writes code? Please select one of the following options that best describes you today.,MC,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new coding skill/programming language in the last year?,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning AI programming or AI-enabled tooling on your own or at work?,MC,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Select all that apply.,MC,NaN,NaN
LanguagesWantEntry,QID52,"Was the programming language you want to use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you want to use next year</strong>.",TE,NaN,NaN
LanguagesHaveEntry,QID51,"Was the programming language you use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you used in the past year</strong>.",TE,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and markup languages in the last year or do you plan to in the year to come? Here, we are referring to anything you use that is conventionally referred to as code.",MC,NaN,NaN
Language,QID34,"Which <b>programming, scripting, and markup languages</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
JobSatPoints_9,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Innovation through solving challenging and complex problems,10.0
JobSatPoints_8,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Job stability and career growth with a single employer,9.0
JobSatPoints_7,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Solving real-world problems,8.0
JobSatPoints_6,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Developing specialized expertise,7.0
JobSatPoints_5,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Opportunities to mentor and lead junior-level coworkers,6.0
JobSatPoints_4,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Expert mentors,5.0
JobSatPoints_3,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Collaboration and support from a team,4.0
JobSatPoints_2,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_16,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,You like your manager,3.0
JobSatPoints_15_TEXT,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Other (please specify): - Text,15.0
JobSatPoints_15,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Other (please specify):,15.0
JobSatPoints_14,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Recognition from leadership for your work,14.0
JobSatPoints_13,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Recognition from peers for your work,13.0
JobSatPoints_11,QID27,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Competitive pay and benefits,12.0

## Filter rows with a boolean condition
Storing a condition in a variable (`high_salary`) before using it is the pandas equivalent of a SQL `WHERE` clause — here, `CompTotal > 1,000,000` flags every row where total compensation exceeds $1M. `.loc[condition, columns]` then returns only the matching rows, limited to the columns of interest.

In [ ]:
high_salary = df['CompTotal'] > 1000000

In [ ]:
df.loc[high_salary, ['Country', 'Industry', 'CompTotal']]

## Filter by a list of values with `.isin()`
`.isin(list)` is the pandas equivalent of SQL's `WHERE column IN (...)` — checks whether each row's value in `Country` matches any value in the given list, instead of writing a separate `==` condition for each country.

In [ ]:
countries = ['United States', 'India', 'Germany', 'Canada']
filt = df['Country'].isin(countries)

In [ ]:
df.loc[filt, 'Country']

## Filter text columns with `.str.contains()`
`.str.contains('text')` is the pandas equivalent of SQL's `WHERE column LIKE '%text%'` — finds rows where the column contains the given substring anywhere, not just an exact match. `na=False` is important here: without it, any missing (NaN) value in the column would raise an error instead of simply being treated as "doesn't match".

In [ ]:
ai_filt = df['AIAgentExternal'].str.contains('ChatGPT', na=False)

In [ ]:
df.loc[ai_filt, 'AIAgentExternal']